### ISSUE TITLE
Questions about fisheye images

### ISSUE THREAD

**Issue by notabigfish** [jarvishou829/SUPS#10]
Hi,

thanks for your work. I have two questions:

Q1: May I ask how to get the original fisheye images? I am new to Unity and LGSVL. Here are my simple train of thoughts:
1. install Unity and LGSVL
2. load scene into the engine
3. run the scene and capture fisheye images
Are the above steps correct? Thanks!

Q2: Will you annotate 3D obstacles in the future? such as cars and pedestrian. Thank you.

**Comment by jarvishou829** [comment]
Q1: For simple usage of our recored data. You can just download the rosbag file in the data link, and just get the fisheye images from the rosbag. If you want to record the data by your self, you can get instruction  from [LGSVL](https://github.com/lgsvl/simulator). However the LGSVL simulator stopped maintenance last year. Our dataset was set up and recorded using previous online platforms, without attempting an offline solution. The plan for using the simulator offline has been announced in its [issue](https://github.com/lgsvl/simulator/issues/1994.) After learning this news, in order to make it more widely available for future use, we opened up the entire scenario's build, sensor reference configuration, and other files, which are also linked to the disk link.

Q2: As can be seen in our paper, some categories of objects has already been annotated, such as cars, pillars, obstacles. Howerver we did not include pedestrains in our simulated scene. For further study, you can try to add it according to LGSVL tutorial.

**Comment by notabigfish** [comment]
Thank you for this detailed answer. I'll try.
