### ISSUE TITLE
SVL用不了了怎么办呀，一直连接不上

### ISSUE THREAD

**Issue by Fzx-fire** [jarvishou829/SUPS#7]
。

**Comment by jarvishou829** [comment]
Thank you very much for your recognition and support of our work. [LGSVL](https://github.com/lgsvl/simulator) emulator stopped maintenance last year. Our dataset was set up and recorded using previous online platforms, without attempting an offline solution. The plan for using the simulator offline has been announced in its [issue](https://github.com/lgsvl/simulator/issues/1994). After learning this news, in order to make it more widely available for future use, we have also opened up the entire scenario's build, sensor reference configuration, and other files, which are also linked to the disk link. But unfortunately, there is a lot of work currently underway that I cannot verify the route of its publicly available offline simulator solution. However, based on the previous recording experience, with the presence of scenes and vehicle sensor configuration files, it is entirely possible to capture data on offline platforms, which are currently available.
